"""Main application module.

Generated by AES scaffolding.
Edit this file to define your application's main logic.
"""

__version__ = "0.1.0"


def main() -> None:
    """Primary application entry point."""
    print("Hello from AES project!")


if __name__ == "__main__":
    main()
